version: "3.9"

services:

  redis:
    image: redis:7
    container_name: ims_redis
    ports:
      - "6379:6379"
    restart: always

  mongodb:
    image: mongo
    container_name: ims_mongodb
    ports:
      - "27017:27017"
    restart: always

  postgres:
    image: postgres:15
    container_name: ims_postgres
    environment:
      POSTGRES_USER: ims
      POSTGRES_PASSWORD: ims
      POSTGRES_DB: ims_db
    ports:
      - "5432:5432"
    restart: always

  backend:
    build: ./backend
    container_name: ims_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongodb
      - redis
    restart: always
